### ISSUE TITLE
Most mechine have no recipe

### ISSUE THREAD

**Issue by baifeiajdj** [ChildCommunitCN/GregTech-ChildHappyEdition#3]
### GregTech CEu Version

v2.7.3

### Addons Installed

...

### Environment

singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

NO recipe most mechine

### Actual Behavior

.

### Steps to Reproduce

..

**Comment by Darknight123MC** [comment]
I'm sorry and I fixed it in latest release

**Comment by baifeiajdj** [comment]
is great!Thank you!
