### ISSUE TITLE
为什么蒸汽轮机通入蒸汽后不发电

### ISSUE THREAD

**Issue by harmonicola** [ChildCommunitCN/GregTech-ChildHappyEdition#5]
### Your Question

即使在只安装本Mod与JEI的情况下，基础蒸汽轮机与进阶蒸汽轮机通入蒸汽后都不工作，涡轮蒸汽轮机会有工作动画但不发电

**Comment by Darknight123MC** [comment]
可能是一个bug，我查查

**Comment by Darknight123MC** [comment]
0.0.3修复了这个bug。
0.0.3 fixed this bug.
